title: FBIMS
description: Documentation for the Food Bank Inventory Management System
theme: just-the-docs

url: https://codevalve.github.io/fbims-docs
baseurl: ""

aux_links:
  GitHub Repository: https://github.com/codevalve/foodbank

# Enable search
search_enabled: true

# Enable anchor links
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2024 Food Bank Inventory Management System. Distributed under an <a href=\"https://github.com/codevalve/foodbank/tree/main/LICENSE\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Enable copy button on code blocks
enable_copy_code_button: true

# Color scheme
color_scheme: light

# Navigation
nav:
  - title: User Guide
    url: /user-guide
  - title: Technical Docs
    url: /technical
  - title: Project Info
    url: /project
  - title: Admin Guide
    url: /admin
